// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxygvwmthauvrzsmkvkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4eWd2d210aGF1dnJ6c21rdmtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NjE0NDEsImV4cCI6MjA2MzQzNzQ0MX0.8kF4haQLqJyVTthoD_z-f9rG7vBSy8pXnVB-vmyYRCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);